### ISSUE TITLE
Validate ICodeLensProvider API

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/codelens-eclipse#1]
@mickaelistria @mniewrzal if you are interested by CodeLens it should be cool if you could implement CodeLens inside lsp4e. I have written a quick tutorial to implement CodeLens at 
https://github.com/angelozerr/codelens-eclipse/wiki/CodeLens-Extension-Point

**Comment by angelozerr** [comment]
@fabioz perhaps you could be interested with CodeLens too. I ping you, any feedback are welcome!

Here a demo with typescript.java:

![typescriptcodelensdemo](https://user-images.githubusercontent.com/1932211/27044001-576f951a-4f9c-11e7-9338-e08a0c1e6f81.gif)

**Comment by fabioz** [comment]
Hi Angelo,

Interesting concept, however, I must say that  think the space spent for the reference/implementation number is too much waste of space, and if I want the info there are shortcuts for it already through `Ctrl+Shift+G`, `Ctrl+G` or `F4`.

I do think there's a case where decorations would be useful with values of the debugger -- but then, this may be a separate feature...

After seeing https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup, I think a better approach could be creating  a lightweight dialog (such as the one to select a new editor with Ctrl+F6) to request a code lens for some class and a floating view with an editor if it points to some code for the user to see (which the user could dispose easily or dock for reference later on).

**Comment by angelozerr** [comment]
> but then, this may be a separate feature...

The idea is to support that and I have a lot of ideas like display test result before eacj JUnit Test, give the capability to Run a given JUnit Test by drawing a Run icon, etc

> I think a better approach could be creating a lightweight dialog (such as the one to select a new editor with Ctrl+F6) to request a code lens for some class and a floating view with an editor if it points to some code for the user to see (which the user could dispose easily or dock for reference later on).

Yes we can imagine other behaviours, but the main issue is to manage a virtual line (I have called that view zone like VSCode) inside the StyledText.

@fabioz thanks for your feedback

**Comment by angelozerr** [comment]
I think API si now good, it uses CompletableFuture. See https://github.com/angelozerr/codelens-eclipse/blob/master/org.eclipse.codelens/src/org/eclipse/jface/text/provisional/codelens/ICodeLensProvider.java
